Updating to use es6 classes + updating dependencies
antinomy-studio/size pull request #1
Opened 2022-07-19 08:38 UTC by gwen-bo

Updating package to use es6 + updating (dev)dependencies

**Tests**:
- [x] Using the `npm link`-command in a test project 
- [x] Passing the test scripts

2022-07-19 09:16 UTC, antinomy-studio requested changes
Let me know what you think :)

2022-07-19 09:16 UTC, antinomy-studio commented on src/index.js
> +    this.isLandscape = false
I'm wondering if we should still have these in the module? I don't think we're using it at all.

2022-07-19 09:16 UTC, antinomy-studio commented on src/index.js
> +  }
I'm also open to suggestions here; should we keep `size.addListener` and `size.removeListener` as the function names? I am thinking it might make more sense to just use `size.add` and `size.remove`, just like `gsap.ticker.add` / `gsap.ticker.remove`. We might also just add two new functions, `add` and `remove` so that backward compatibility still work?

— what do you think? cc @gwen-bo @PaulBouisset

2022-07-19 09:16 UTC, antinomy-studio commented on src/index.js
> +    size.unbind();
I don't think we have access to `size` here? Also, we mostly just `bind` it once, so I believe we can remove that.

2022-07-19 09:21 UTC, PaulBouisset commented on src/index.js
> +  }
Agree @antinomy-studio , we keep these for backward compatibility but I like the `size.add` !

2022-07-19 09:28 UTC, gwen-bo commented on src/index.js
> +    size.unbind();
Ah sorry, my bad, seems like I didn't test that function with the test script! Do you want me to remove it or do I just rework it so the unbind does work? :)

2022-07-19 09:30 UTC, gwen-bo commented on src/index.js
> +    this.isLandscape = false
Agreed! the `isLandscape` was used nowhere, although we could update this on the `orientation change` you suggested? The `hasBar` is updated on the event itself, but not too sure what it is used for? :)

2022-08-08 09:51 UTC, baptistebriel commented on src/index.js
> +    this.isLandscape = false
Yes! Updating `isLandscape` on orientation change would make sense. The `hasBar` was used previously on iOS to know if the bottom bar collapsed on scroll, or not :)

2022-08-08 16:32 UTC, antinomy-studio approved these changes

2022-08-08 16:32 UTC, merged